bb3mobi_medals_controller:
    path: /badges
    defaults: { _controller: bb3mobi.medals.controller:medals_system }

bb3mobi_medals_categorypage:
    path: /badges/{category_id}
    defaults:
        _controller: bb3mobi.medals.controller:medals_category
        page: 1
        title: ''
    requirements:
        category_id: \d+

bb3mobi_medals_awardsage:
    path: /badges/awards/{user_id}
    defaults:
        _controller: bb3mobi.medals.controller:medals_awards
        page: 1
        title: ''
    requirements:
        category_id: \d+